### ISSUE TITLE
OAuth con Google

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/webMarcaPersonalFPEstudiantes#22]
Para la autenticación con la plataforma decidimos utilizar la autenticación con Google a través de OAuth y Laravel/Socialite.

Los pasos para el desarrollo completo de la autenticación los tenéis en [esta tarea del aula virtual](https://aulavirtual.murciaeduca.es/mod/assign/view.php?id=3530394)

No obstante, para que no haya problemas con la configuración de la aplicación en Google Cloud, os facilitaré, por correo, las credenciales de una aplicación que yo ya he configurado. Por lo tanto, podéis comenzar desde el apartado **Instalar Socialite**.

Ya que el frontend lo tenemos desplegado en otro repositorio, una pequeña mejora sería la de incorporar la sustitución en el cliente del formulario de login por el botón de autenticación con Google.

**Comment by AndresEsparzaALU** [comment]
Parece ser que alu.murciaeduca.es es un dominio distinto de murciaeduca.es, o al menos es a la conclusión que llego por este mensaje de error

![image](https://github.com/2DAW-CarlosIII/webMarcaPersonalFPEstudiantes/assets/114472526/6f2c2742-b71e-4009-b2d4-8b07ff4f3503)

**Comment by AndresEsparzaALU** [comment]
creando una aplicación propia en Google cloud con mi cuenta personal si he conseguido registrar un usuario en la aplicación, eso sí, podrá hacerlo cualquier usuario con cuenta de Google.

![image](https://github.com/2DAW-CarlosIII/webMarcaPersonalFPEstudiantes/assets/114472526/f38b93ea-07e4-4f2c-ad8b-a72764255f32)

**Comment by albsierra** [comment]
Me temía que el subdominio no fuera admitido como dominio de dentro de la organización.
Los dominios se pueden restringir con la [propiedad hd](https://laravel.com/docs/socialite#optional-parameters).

El parámetro aceptará un array de dominios válidos.
```
use Laravel\Socialite\Facades\Socialite;
 
return Socialite::driver('google')
    ->with(['hd' => ['murciaeduca.es', 'alu.murciaeduca.es']])
    ->redirect();
```

Cuando tengamos un dominio para la aplicación, tendremos que hacer ajustes en el cliente OAuth
