### ISSUE TITLE
Solo backend

### ISSUE THREAD

**Issue by albsierra** [2DAW-CarlosIII/webMarcaPersonalFPEstudiantes#27]
Veo que habéis eliminado toda las vistas del frontend en Laravel, así como el `package.json`.

En ese caso, también deberíais eliminar los archivos:

- [jsconfig.json](https://github.com/2DAW-CarlosIII/webMarcaPersonalFPEstudiantes/blob/master/jsconfig.json)
- [package-lock.json](https://github.com/2DAW-CarlosIII/webMarcaPersonalFPEstudiantes/blob/master/package-lock.json)
- [postcss.config.js](https://github.com/2DAW-CarlosIII/webMarcaPersonalFPEstudiantes/blob/master/postcss.config.js)
- [tailwind.config.js](https://github.com/2DAW-CarlosIII/webMarcaPersonalFPEstudiantes/blob/master/tailwind.config.js)
- la carpeta [.vite](https://github.com/2DAW-CarlosIII/webMarcaPersonalFPEstudiantes/tree/master/.vite).

**Comment by albsierra** [comment]
Con esa decisión, entiendo que la autenticación con Google la haréis desde el frontend??

**Comment by JaimeLloretGarcia** [comment]
Buenas noches Alberto,
Mañana nos gustaría hablar contigo en persona, si es posible, para resolver algunas dudas que nos han surgido, sobre todo con la utilización de React-admin.
¿Estarás mañana por el centro?

Muchas gracias!

**Comment by albsierra** [comment]
Sí. Está mañana estaré en el centro hasta las 13:00
