### ISSUE TITLE
Google Oauth excepcion 

### ISSUE THREAD

**Issue by AndresEsparzaALU** [2DAW-CarlosIII/webMarcaPersonalFPEstudiantes#30]
![image](https://github.com/2DAW-CarlosIII/webMarcaPersonalFPEstudiantes/assets/114472526/ebf8e95b-e453-409d-b719-bac5cd7ea519)
He seguido los pasos al pie de la letra pero a la hora de hacer el callback de google salta una excepción.

**Comment by AndresEsparzaALU** [comment]
![image](https://github.com/2DAW-CarlosIII/webMarcaPersonalFPEstudiantes/assets/114472526/f83afd03-6f90-467d-ae13-e711d12c7660)

Se ve que ahora está mas hablador

**Comment by AndresEsparzaALU** [comment]
*Nota, he vuelto de laravel breeze api a laravel breeze react

**Comment by albsierra** [comment]
Ese error parece un error de red más que  de Laravel. 
Prueba a hacer ping a www.googleapis.com
